colleges/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('marks_system/',include('marks_system.urls')),
    path('admin/', admin.site.urls),
]

marks_system/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'marks_system'
urlpatterns = [
    path('', views.index),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('user_creation/', views.user_creation, name='user_creation'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('add_students_marks/', views.add_students_marks, name='add_students_marks'),
    path('students_marklist/', views.students_marklist, name='students_marklist'),
    path('edit_marks/<int:pk>', views.edit_marks, name='update_marks'),
    path('delete_student/<int:pk>', views.delete_student, name='delete_student'),
    path('department_creation/', views.department_creation, name='department_creation')

]

templates/add_departments.html
{% extends 'base.html' %}
{% block cotent %}
    {% if  message %}
        {{ message }}
    {% endif %}
    <form action="{% url 'marks_system:department_creation' %}" method="post">{% csrf_token %}
       <table style="text-align: left">
           {{ departmentcreationform.as_table }}
       </table>
        <input type="submit" style="margin:2mm 4cm" value="ADD">
    </form>
{#    <h3><a style="text-decoration: none" href="{% url 'marks_system:students_marklist' %}" >Students mark list</a></h3>#}

{% endblock %}

templates/add_marks.html
{% extends 'base.html' %}
{% block cotent %}
    {% if  message %}
        {{ message }}
    {% endif %}
    <form action="{% url 'marks_system:add_students_marks' %}" method="post">{% csrf_token %}
       <table style="text-align: left">
           {{ add_marks_form.as_table }}
       </table>
        <input type="submit" style="margin:2mm 4cm" value="ADD">
    </form>
    <h3><a style="text-decoration: none" href="{% url 'marks_system:students_marklist' %}" >Students mark list</a></h3>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<body>
    <h3>
         Hi {{ request.user}} &nbsp;&nbsp;
         <a href="{%url 'marks_system:dashboard'%}">Dashboard</a>&nbsp;&nbsp;
        <a href="{%url 'marks_system:logout' %}">Logout</a>&nbsp;&nbsp;&nbsp;
         Last logined : {{ request.user.last_login }}
     </h3>
    {% block cotent %}

    {% endblock %}
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% block cotent %}
    <h2>Welcome to Dashboard</h2>
    <h3>
        <a style="text-decoration: none" href="{% url 'marks_system:user_creation' %}" >Create user</a>&nbsp;&nbsp;&nbsp;&nbsp;
        <a style="text-decoration: none" href="{% url 'marks_system:department_creation' %}" >Create Department</a>&nbsp;&nbsp;&nbsp;
        <a style="text-decoration: none" href="{% url 'marks_system:add_students_marks' %}" >Add student's marks</a>&nbsp;&nbsp;
        <a style="text-decoration: none" href="{% url 'marks_system:students_marklist' %}" >Students marklist</a>

    </h3>
{% endblock %}

templates/edit_marks.html
{% extends 'base.html' %}
{% block cotent %}
    {% if  message %}
        {{ message }}
    {% endif %}
     <h3>"{{ edit_student.student_name }}" details are below:</h3>
    <form action="{% url 'marks_system:update_marks' pk=edit_student.id %}" method="post">{% csrf_token %}
       <table style="text-align: left">
           {{ editform.as_table }}
       </table>
        <input type="submit" style="margin:2mm 4cm" value="ADD">
    </form>
    <a style="text-decoration: none" href="{% url 'marks_system:students_marklist' %}" >Students marklist</a>

{% endblock %}

templates/index.html
<!DOCTYPE html>
<html>
<body>
<h1>Welcome to Student's Marks System</h1>

<h4>
    <a href="{% url 'marks_system:login' %}">Login</a> &nbsp;&nbsp;
{#    <a href="{% url 'marks_system:signup'%}">signup by student</a>#}
</h4>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<body>
<h1>Welcome to Student's Marks System</h1>


<form action="{% url 'marks_system:login' %}" method="post">{% csrf_token %}
    {{ login_form.as_p }}
    <input type="submit" value="Login">
</form>

{%if message %}
    {{ message }}
{% endif %}

<br>
{#<a href="/students_details/signup">Signup</a> &nbsp;&nbsp;#}
{#<a href="{% url 'marks_system' %}">Home</a>#}
</body>
</html>

templates/logout.html
<!DOCTYPE html>
<html>
<body>

   <h3> {{ user }} is logout sucessfully</h3>

<br>
<a href="{% url 'marks_system:login' %}">Login again</a> &nbsp;&nbsp;

</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html>
<body>
<h1>Welcome to Student's Marks System</h1>

<a href="{% url 'marks_system:principal' principal='principal' %}">principal</a>
<a href="{% url 'marks_system:principal' principal='principal' %}">principal</a>
<a href="{% url 'marks_system:principal' principal='principal' %}">principal</a>
<a href="{% url 'marks_system:principal' principal='principal' %}">principal</a>
</body>
</html>

templates/student_name_list.html
{% extends 'base.html' %}
{% block cotent %}
    {% if message %}
        {{ message }}
    {% endif %}
        <a style="text-decoration: none" href="{% url 'marks_system:students_marklist' %}" >Students marklist</a>

    <table border="1">
        <tr>
            <th>Student Name</th>
            <th>Department</th>
            <th>Semester</th>
            <th>Tamil</th>
            <th>English</th>
            <th>Maths</th>
            <th>Science</th>
            <th>Social Science</th>
            <th>Total</th>
            <th>Added by</th>
            <th>Delete</th>
        </tr>
{#        for details in students_list():#}
{#        user_dept = details.department#}
{#        print(user_dept.department_name)#}
        {% for details in students_list %}
            <tr>
                <td align="center"><a style="text-decoration: none" href="{% url 'marks_system:update_marks' details.pk %}"> {{ details.student_name }}</a></td>
                <td align="center">{{ details.department.department_name }} </td>
                <td align="center">{{ details.semester }}</td>
                <td align="center"> {{ details.tamil }}</td>
                <td align="center"> {{ details.english }}</td>
                <td align="center"> {{ details.maths }}</td>
                <td align="center"> {{ details.science }}</td>
                <td align="center"> {{ details.socialscience }}</td>
                <td align="center"> {{ details.total_marks }}</td>
                <td align="center"> {{ details.created_by }}</td>
                <td align="center"><a href="{% url 'marks_system:delete_student' details.pk %}"> [x]</a></td>
            </tr>
        {% endfor %}
        &nbsp;&nbsp;
    </table>
   <h3><a style="text-decoration: none; margin-top: 10px;float:left;" href="{% url 'marks_system:add_students_marks' %}" >Add another student's marks</a></h3>
{% endblock %}

templates/user_creation.html
{% extends 'base.html' %}
{% block cotent %}

{#    <h3>Welcome to {{ request.user }} Dashboard</h3>#}
    {% if  message %}
        {{ message }}
    {% endif %}
    <form action="{% url 'marks_system:user_creation' %}" method="post">{% csrf_token %}
        <table style=" text-align: left">

            {{ UserCreationForm.as_p }}

            {% if request.user.is_superuser %}
                <label style="margin-right: 42px">User role:</label>
                <select name="user_type"> user_type
                  <option selected value="superadmin">Superadmin</option>
                </select>
            {% elif request.user.is_superadmin %}
                <label style="margin-right: 42px">User role:</label>
                <select name="user_type"> user_type
                  <option selected value="principal">Principal</option>
                </select>
            {% elif request.user.is_principal  %}
                <label style="margin-right: 42px">User role:</label>
                <select name="user_type">
                  <option selected value="Select" disabled>Select</option>
                  <option value="HOD">HOD</option>
                  <option value="Staff">Staff</option>
                </select>
            {% elif request.user.is_hod  %}
                <label style="margin-right: 42px">User role:</label>
                <select name="user_type">
                  <option selected value="Select" disabled>Select</option>
                  <option value="Student">Student</option>
                  <option value="Staff">Staff</option>
                </select>
            {% elif request.user.is_staff  %}
                <label style="margin-right: 42px">User role:</label>
                <select name="user_type">
                  <option value="Student">Student</option>
                </select>
            {% endif %}
        </table>
        <input style="margin-top: 20px;margin-left: 100px" type="submit" value="Create user">
    </form>
{% endblock %}